version: '3.7'

services:
  transaction-api:
    container_name: transaction-api
    build: .
    env_file: .env
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - transaction-net
  transaction-db:
    image: postgres
    container_name: transaction-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - transaction-net

volumes:
  db-data:

networks:
  transaction-net:
    driver: bridge
